CREATE TABLE CLASSES (
	ID_CLASS INT  GENERATED ALWAYS AS IDENTITY,
	CLASS_NAME VARCHAR(40) NOT NULL,
	PRIMARY KEY (ID_CLASS)
);

CREATE TABLE ACTIVITIES (
	ID_ACTIVITY INT GENERATED ALWAYS AS IDENTITY,
	ID_CLASS INT,
	NAME_ACTIVITY VARCHAR(40) NOT NULL,
	DIFFICULTY INT NOT NULL,
	STATUS_ACTIVITY BOOL,
	STATUS_CONCLUSION_DATE BOOL,
	CONCLUSION_DATE DATE,
	EXPIRATION_DATE DATE,
	
	PRIMARY KEY (ID_ACTIVITY),
	CONSTRAINT FK_CLASSES
		FOREIGN KEY (ID_CLASS)
			REFERENCES CLASSES (ID_CLASS)
);